### PR TITLE
Update README.md to use most current version of dat repo in instructions

### PR DESCRIPTION
**Pull request by JHibbard**
## Description

Updated README.md to use most current version of `dat` repo in download instructions.

## How was this patch tested?

Documentation update, no tests needed.

## Does this require an update to the documentation?

Yes, this is a docs update.

### CODE REVIEW

**Review by wjones127 — APPROVED** [review]
It would be nice if this automatically updated. Not sure the best way to accomplish this (maybe using quarto to github markdown + a CI check?)

**Comment by MrPowers** [comment]
@JHibbard - looks like this changes to v0.0.2.  Can you update the rest of the README to reflect the directory changes that were made in the v0.0.2 release as well?

**Comment by MrPowers** [comment]
@JHibbard - these changes look good to me.  Looks like the CI is failing.  Can you please take a look?

**Comment by MrPowers** [comment]
Can you please rebase off the latest version of master?  That should fix the build for this branch.

**Comment by JHibbard** [comment]
@MrPowers Thanks for taking a look, I think we're good to go now.

**Pull request merged**
